# Generated by Django 4.2 on 2023-05-02 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='제목')),
                ('content', models.CharField(max_length=30000, verbose_name='본문')),
                ('written_at', models.DateField(verbose_name='작성일')),
                ('url', models.CharField(max_length=2000, verbose_name='주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100, verbose_name='단어')),
                ('frequecny', models.IntegerField(default=1, verbose_name='빈도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.article', verbose_name='기사')),
            ],
            options={
                'db_table': 'words',
            },
        ),
    ]
