# Generated by Django 4.2 on 2023-05-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('article_id', 'text'), name='unique_article_text'),
        ),
    ]
